import React from 'react';
import Layout from '../components/layout';
import SEO from '../components/seo';

const DataPage = () => {
  return (
    <Layout>
      <SEO title="Data" />
      <h1>Data</h1>
      <p>
        This page lists each of the download links for data that is generated by
        the Spotlight scans
      </p>
      <ul className="usa-list">
        {[
          'dap',
          'pagedata',
          '200scanner',
          'sitemap',
          'pshtt',
          'uswds2',
          'lighthouse',
          'privacy',
          'third_parties',
        ].map(scan => {
          const url = `https://site-scanning.app.cloud.gov/api/v1/scans/${scan}/`;
          return (
            <li>
              <a href={url}>{url}</a>
            </li>
          );
        })}
      </ul>
    </Layout>
  );
};

export default DataPage;
