import React from 'react';
import Layout from '../components/layout';
import SEO from '../components/seo';

const DataPage = () => {
  return (
    <Layout>
      <SEO title="Data" />
      <h1>Data</h1>
      <p>
        This page lists each of the download links for data that is generated by
       each scan.
      </p>
    <h3>Digital Analytics Program Scan</h3>
    <ul>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/dap/">Scan Data (JSON)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/dap/csv/">Scan Data (CSV)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/dap/18f.gov">Scan Data for a Particular Website (e.g. 18f.gov)</a></li>
    </ul>
    <h3>Lighthouse Scan</h3>
    <ul>
    <ul>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/lighthouse/">Scan Data (JSON)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/lighthouse/csv/">Scan Data (CSV)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/lighthouse/18f.gov">Scan Data for a Particular Website (e.g. 18f.gov)</a></li>
    </ul>
    <h3>Page Data Scan</h3>
    <ul>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/pagedata/">Scan Data (JSON)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/pagedata/csv/">Scan Data (CSV)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/pagedata/18f.gov">Scan Data for a Particular Website (e.g. 18f.gov)</a></li>
    </ul>
    <h3>Privacy Page Scan</h3>
    <ul>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/privacy/">Scan Data (JSON)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/privacy/csv/">Scan Data (CSV)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/privacy/18f.gov">Scan Data for a Particular Website (e.g. 18f.gov)</a></li>
    </ul>
    <h3>Security Scan</h3>
    <ul>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/pshtt/">Scan Data (JSON)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/pshtt/csv/">Scan Data (CSV)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/pshtt/18f.gov">Scan Data for a Particular Website (e.g. 18f.gov)</a></li>
    </ul>
    <h3>Sitemap Scan</h3>
    <ul>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/sitemap/">Scan Data (JSON)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/sitemap/csv/">Scan Data (CSV)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/sitemap/18f.gov">Scan Data for a Particular Website (e.g. 18f.gov)</a></li>
    </ul>
    <h3>Status Scan</h3>
    <ul>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/200scanner/">Scan Data (JSON)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/200scanner/csv/">Scan Data (CSV)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/200scanner/18f.gov">Scan Data for a Particular Website (e.g. 18f.gov)</a></li>
    </ul>
    <h3>Third Party Services Scan</h3>
    <ul>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/third_parties/">Scan Data (JSON)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/third_parties/csv">Scan Data (CSV)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/third_parties/18f.gov">Scan Data for a Particular Website (e.g. 18f.gov)</a></li>
    </ul>
    <h3>US Web Design System Scan</h3>
    <ul>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/uswds2/">Scan Data (JSON)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/uswds2/csv/">Scan Data (CSV)</a></li>
    <li><a href="https://site-scanning.app.cloud.gov/api/v1/scans/uswds2/18f.gov">Scan Data for a Particular Website (e.g. 18f.gov)</a></li>
    </ul>
    </Layout>
  );
};

export default DataPage;
